### ISSUE TITLE
What is this repo about? 

### ISSUE THREAD

**Issue by ajay01994** [allenai/allennlp-reading-comprehension-research#2]
Hi all,
Thanks for MRC, what is this repo about? Just curious, I am very interested in  Machine reading comprehensions and Squad 2.0 leader board is there where Allen AI model was there only in the month of May, haven't heard much on MRC from Allen ai after that :)

**Comment by matt-gardner** [comment]
This is where we are working on research projects. It is public only for convenience, and we are not publicly supporting anything in this repo, nor answering questions. If people open issues on here, they will probably be closed without comment. I'll update the README with this information soon.
